### ISSUE TITLE
Bottom buttons are cut off

### ISSUE THREAD

**Issue by apesic** [apesic/rpncalc#1]
On smaller phones, the layout overflows the bottom of the display:
![image](https://user-images.githubusercontent.com/442404/103104169-8286ee00-45da-11eb-96f4-5238632b6e8d.png)

**Comment by sphh** [comment]
On an even smaller screen, it looks even worse:
![Screenshot_20201228-154419](https://user-images.githubusercontent.com/4856462/103230473-762dc880-492d-11eb-9068-1e9c93cda86f.png)

Thanks for looking into this!

**Comment by apesic** [comment]
Should be fixed with release [v1.0.2](https://github.com/apesic/rpncalc/releases/tag/v1.0.2), tested it on even very tiny screen sizes now. Will be available through Google Play in a few days. @sphh thanks for the report, let me know if you're still seeing any problems.

**Comment by sphh** [comment]
Thanks!! I will definitely check it, when the new version appears in F-Droid.

I am also looking forward to the scientific mode.

**Comment by sphh** [comment]
Now that F-Droid has picked up the latest build (1.0.3) I can finally confirm that no buttons are cut off. Thanks!

But now there is #4 ...
