### ISSUE TITLE
Screen turns grey after division by zero.

### ISSUE THREAD

**Issue by Liorst4** [apesic/rpncalc#11]
Steps to reproduce:
* Press 1
* Press ↵
* Press 0
* Press ÷
* Press ÷ again
* Screen turn grey

Using the 1.2.0 version from F-Driod (https://f-droid.org/repo/dev.pesic.rpncalc_7.apk)

**Comment by wviana** [comment]
Could not reproduce. Can you try again in current version?

**Comment by apesic** [comment]
Ya, this should be fixed in the current version. Closing for now but lmk if you're still having problems.
