### ISSUE TITLE
Can't handle exponents with repeating decimals

### ISSUE THREAD

**Issue by anaskaejdar** [apesic/rpncalc#12]
Basically I'm trying to calculate 2^(1/24),

![Screenshot_۲۰۲۱۱۲۰۳-۲۳۴۳۴۴](https://user-images.githubusercontent.com/32847759/144700492-fcd61d1f-5a9d-4f62-8eaf-bac837fd809f.jpg)

but after _this_ button press on the yˣ button,

![Screenshot_۲۰۲۱۱۲۰۳-۲۳۴۳۵۰](https://user-images.githubusercontent.com/32847759/144700494-67a5f1b2-44f5-4ed9-aab1-f5474205df4c.jpg)

the app freezes, and any subsequent button presses turns the whole screen grey.

It's a different story entirely with a simpler exponent like 2^(1/4)

**Comment by wviana** [comment]
Is it the right way to enter your expression?
Thought it should be something as this:
```
2
1
14
÷
yˣ
```

**Comment by anaskaejdar** [comment]
> Is it the right way to enter your expression? Thought it should be something as this:
> 
> ```
> 2
> 1
> 14
> ÷
> yˣ
> ```

That is the same order as what I posted, except you have 14 where I had 24

**Comment by wviana** [comment]
Oh, ok my bad, I confused it.
So trying using current version I got into the result of  `1.029302236643492`.
It matches same expression in python interpreter. Looks like it was changed the "calculator engine" now it's using an external lib to do the math, looks to work better.

**Comment by wviana** [comment]
Look at [this issue](https://github.com/apesic/rpncalc/issues/5), looks like the mantainer already pushed this lib usage. Probably they should close this linked issue.

**Comment by anaskaejdar** [comment]
The last F-Droid release was June 2021 (six months _later_ than the last github release), but that fdroid release must have had this bug, since I reported it in December 2021.

**Comment by wviana** [comment]
Oh, so the F-Droid is way behind master.
Will try to configure a git action to build apk and place it into the release.
