### ISSUE TITLE
UI issue + feedback

### ISSUE THREAD

**Issue by reitrop** [apesic/rpncalc#3]
Hello,

I just created a GitHub account to give you some feedback on your application. I recently discovered it while searching for RPN calculators on F-Droid.

First, I have an issue with the bottom of the screen. The “Back/Home/Apps” bar of Android is overlapping the bottom of the view, making the 0, comma, Erase and Enter buttons smaller and hard to read. See picture bellow:
![Screen RPN](https://user-images.githubusercontent.com/77442699/104589188-c9ac5000-5669-11eb-87b8-684bc709c530.png)

Second, you included a “1/X” button, but I would have preferred an exponent button. Inverse is pretty limiting, whereas exponent are often used, can cover roots… or even inverse. I know this is a bit nerdy, but I guess non-nerdy people don’t use RPN in the first place.

Otherwise, I think it’s a very elegant application. I really like the colour and size of the buttons, fonts are clean, you don’t feel overwhelmed like on some apps that try to emulate old HP calculators.

**Comment by apesic** [comment]
Thanks for the feedback, and I'm glad you're enjoying the app!

> First, I have an issue with the bottom of the screen. The “Back/Home/Apps” bar of Android is overlapping the bottom of the view, making the 0, comma, Erase and Enter buttons smaller and hard to read. 

That's unfortunate--thought I had fixed this in v1.0.2, but looks like there's still a bug. To help me track down the issue with the button overlap, could you let me know:
- what phone you use
- what version of Android you're on
- what version of the RPNcalc app you have (hit the three dots in the top left corner)

> Second, you included a “1/X” button, but I would have preferred an exponent button. Inverse is pretty limiting, whereas exponent are often used, can cover roots… or even inverse. I know this is a bit nerdy, but I guess non-nerdy people don’t use RPN in the first place.

Yeah that's a good point and very reasonable request--I'll make that change in the next release.

**Comment by reitrop** [comment]
Hi,

Here are the information you requested:
- I'm using a Fairphone 3.
- It's running on Android 10.
- Here is where I apologize. I have downloaded the app on F-Droid, where the latest version available is 1.0.1. Seeing your comment, I headed to the Play Store, and tried the v1.0.2. So the bug I described is not present in this latest build. Good news!

Glad I could make a relevant suggestion about that “1/X” button ^^ I'm just gonna wait for v1.0.2 (or further) to be pushed on F-Droid then.

**Comment by apesic** [comment]
> Here is where I apologize. I have downloaded the app on F-Droid, where the latest version available is 1.0.1

Oh that's my mistake, I made an error in my F-Droid metadata that's preventing it from automatically picking up the latest version--I'll push a fix for that ASAP.

**Comment by apesic** [comment]
Fixed with https://github.com/apesic/rpncalc/commit/7ff48aa199ec04778ef90d22fa95a4fc42c439e5, which is included in v1.0.3.

**Comment by reitrop** [comment]
I confirm that v1.0.3 just reached F-Droid, and is working perfectly.
