### ISSUE TITLE
Some keys are missing when app is not running in fullscreen mode

### ISSUE THREAD

**Issue by julien-montmartin** [apesic/rpncalc#6]
Hello! 

Some keys are missing when app is not running in fullscreen mode:

![Screenshot_20210203_190035_dev pesic rpncalc](https://user-images.githubusercontent.com/19656720/106789446-9189a300-6652-11eb-9f37-d9050f6913a0.jpg)

**Comment by apesic** [comment]
Hi Julien, thanks for the feedback.

Can you check what version of the app you're running (hit the three dots in the top left)? I believe this should work correctly in 1.0.2 and later, but F-Droid was stuck on the older build until recently so it's possible you have 1.0.1. If that's the case, try again after an update and let me know.

**Comment by julien-montmartin** [comment]
Indeed! It was 1.0.1. After a manual update (with F-Droid), I have 1.0.3. This newer version fix my issue. Thanks 👍
